intex_org_homepage:
    path:     /
    defaults: { _controller: IntexOrgBundle:Page:index }
    requirements:
             methods:  GET

intex_org_user_show:
    path:  /user/{user_id}
    defaults: { _controller: IntexOrgBundle:User:showUser}
    requirements:
            methods:  GET
            user_id: \d+

intex_org_users:
    path:  /users/
    defaults: { _controller: IntexOrgBundle:User:index }
    requirements:
           methods:  GET

intex_org_companies:
    path:  /companies/
    defaults: { _controller: IntexOrgBundle:Company:index }
    requirements:
            methods:  GET

intex_org_company_show:
    path: /company/{company_id}
    defaults: { _controller: IntexOrgBundle:Company:showCompany }
    requirements:
            methods:  GET
            company_id: \d+

intex_org_company_users:
    path: /userscompany/{company_id}
    defaults: { _controller: IntexOrgBundle:User:listUsers }
    requirements:
            methods:  GET
            company_id: \d+

intex_org_user_new:
     path: /newuserincomp/{company_id}
     defaults: { _controller: IntexOrgBundle:User:newUser }
     requirements:
            methods:  GET
            company_id: \d+

intex_org_user_create:
      path: /createuser/{company_id}
      defaults: { _controller: IntexOrgBundle:User:createUser }
      requirements:
            methods:  POST
            company_id: \d+

intex_org_user_upload:
      path: /upload/
      defaults: { _controller: IntexOrgBundle:Page:uploadXml }


intex_org_user_load:
      path: /load/
      defaults: { _controller: IntexOrgBundle:Page:loadUsers }
      requirements:
            methods:  POST