<?php

namespace Intex\OrgBundle\Entity\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return companies from array $companies that exist in DB
     * @param \Doctrine\ORM\ArrayCollection $companies
     * @return \Doctrine\ORM\ArrayCollection
     */
    public function getExistingCompanies(ArrayCollection $companies)
    {
        $companiesOgrns = array();
        foreach ($companies as $organization){
            $companiesOgrns[] = $organization->getOgrn();
        }

        $db = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.ogrn IN (:ogrns)')
            ->setParameter('ogrns', $companiesOgrns);

        return $db->getQuery()->getResult();
    }
}
