<?php

namespace Intex\OrgBundle\Entity\Repository;


/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
   public function getAllCompanies()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->addOrderBy('c.name', 'ASC');

        return $qb->getQuery()
            ->getResult();
    }

    public function getAllOgrn()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.ogrn');
        return $qb->getQuery()
            ->getResult();
    }

}
