<?php

namespace Intex\OrgBundle\Entity\Repository;
use Intex\OrgBundle\Entity\Company as Company;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getAllCompanies()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->addOrderBy('c.name', 'ASC');

        return $qb->getQuery()
               ->getResult();
    }

    /**
     * @param Company $company
     * @return bool
     */
    public function isUniqueOrganization(Company $company)
    {
        $db = $this->createQueryBuilder('c')
              ->select('c')
              ->where('c.ogrn = :ogrn')
              ->setParameter('ogrn', $company->getOgrn());
        $ogrn = $db->getQuery()
                ->getResult();

        if ($ogrn) {
            return false;
        }
        return true;
    }
}
